In [1]:
import pandas as pd

# change this to the path of the output of detector_evaluation.py
    
df = pd.read_csv(r'results/yoloworld_results_full.csv')

# Filter rows based on column: 'recall'
df = df[df['recall'] > 0.95]

# Filter rows based on column: 'precision'
df = df[df['precision'] > 0.95]

# Sort by column: 'recall' (descending)
df = df.sort_values(['recall'], ascending=[False])

display(df)


# output

# 100	yolov8l-worldv2.pt	['cat', 'dog', 'domestic cat', 'domestic dog', 'sphynx cat', 'bombay cat', 'birman cat', 'tiger', 'big tiger', 'fox', 'wolf', 'coyote', 'drawing', 'painting']	tiger	0.05	0.958041958041958	102	35	5	1	0.9532710280373832	0.9902912621359224	0.9714285714285714

,model_name,class_set,cutoff,confidence_threshold,accuracy,true positive,true negative,false postivie,false negative,precision,recall,f1_score
100,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.05,0.958042,102,35,5,1,0.953271,0.990291,0.971429
150,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.05,0.958042,101,36,4,2,0.961905,0.980583,0.971154
161,yolov8x-worldv2.pt,"['cat', 'dog']",NaN,0.10,0.951049,101,35,5,2,0.952830,0.980583,0.966507
160,yolov8x-worldv2.pt,"['cat', 'dog']",NaN,0.05,0.951049,101,35,5,2,0.952830,0.980583,0.966507
163,yolov8x-worldv2.pt,"['cat', 'dog']",NaN,0.20,0.951049,101,35,5,2,0.952830,0.980583,0.966507
...,...,...,...,...,...,...,...,...,...,...,...,...
68,yolov8m-worldv2.pt,"['cat', 'dog']",NaN,0.45,0.944056,98,37,3,5,0.970297,0.951456,0.960784
51,yolov8m-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.10,0.930070,98,35,5,5,0.951456,0.951456,0.951456
195,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.30,0.930070,98,35,5,5,0.951456,0.951456,0.951456
196,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.35,0.937063,98,36,4,5,0.960784,0.951456,0.956098
197,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.40,0.944056,98,37,3,5,0.970297,0.951456,0.960784

In [ ]:
## fine grained from previous step

import pandas as pd

# change this to the path of the output of detector_evaluation.py

df = pd.read_csv(r'results/yoloworld_results_fine_grained.csv')

# Filter rows based on column: 'recall'
df = df[df['recall'] > 0.95]

# Filter rows based on column: 'precision'
df = df[df['precision'] > 0.95]

# Sort by column: 'recall' (descending)
df = df.sort_values(['recall'], ascending=[False])

display(df)

,model_name,class_set,cutoff,confidence_threshold,accuracy,true positive,true negative,false postivie,false negative,precision,recall,f1_score
39,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.070,0.958042,102,35,5,1,0.953271,0.990291,0.971429
6,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.060,0.958042,102,35,5,1,0.953271,0.990291,0.971429
37,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.050,0.958042,102,35,5,1,0.953271,0.990291,0.971429
38,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.060,0.958042,102,35,5,1,0.953271,0.990291,0.971429
5,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.050,0.958042,102,35,5,1,0.953271,0.990291,0.971429
...,...,...,...,...,...,...,...,...,...,...,...,...
91,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.125,0.944056,99,36,4,4,0.961165,0.961165,0.961165
92,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.150,0.944056,99,36,4,4,0.961165,0.961165,0.961165
93,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.175,0.944056,99,36,4,4,0.961165,0.961165,0.961165
94,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.200,0.944056,99,36,4,4,0.961165,0.961165,0.961165
95,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.250,0.944056,99,36,4,4,0.961165,0.961165,0.961165

In [ ]:
import pandas as pd

# change this to the path of the output of detector_evaluation.py
    
df = pd.read_csv(r'results/yoloworld_results_full_more_thresholds.csv')

# Filter rows based on column: 'recall'
df = df[df['recall'] > 0.95]

# Filter rows based on column: 'precision'
df = df[df['precision'] > 0.95]

# Sort by column: 'recall' (descending)
df = df.sort_values(['recall'], ascending=[False])

display(df)

,model_name,class_set,cutoff,confidence_threshold,accuracy,true positive,true negative,false postivie,false negative,precision,recall,f1_score
85,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.050,0.958042,102,35,5,1,0.953271,0.990291,0.971429
86,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.060,0.958042,102,35,5,1,0.953271,0.990291,0.971429
87,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.070,0.958042,102,35,5,1,0.953271,0.990291,0.971429
7,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.070,0.958042,102,35,5,1,0.953271,0.990291,0.971429
6,yolov8l-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.060,0.958042,102,35,5,1,0.953271,0.990291,0.971429
...,...,...,...,...,...,...,...,...,...,...,...,...
187,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.125,0.944056,99,36,4,4,0.961165,0.961165,0.961165
188,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.150,0.944056,99,36,4,4,0.961165,0.961165,0.961165
189,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.175,0.944056,99,36,4,4,0.961165,0.961165,0.961165
190,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.200,0.944056,99,36,4,4,0.961165,0.961165,0.961165
191,yolov8x-worldv2.pt,"['cat', 'dog', 'domestic cat', 'domestic dog',...",tiger,0.250,0.944056,99,36,4,4,0.961165,0.961165,0.961165